import Head from 'next/head'

const Home = ()=>{
  return (
    <>
      <Head>
        <title>Consultora Enlazar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-blue'>
        <h1 className='text-3xl font-Noah'>
          Creating project!
        </h1>
      </div>
    </>
  );
};
export default Home;